### ISSUE TITLE
error installing to Pi

### ISSUE THREAD

**Issue by handsomedude** [Qortal/UI#12]
yarn run build

all i get is 

yarn run v1.22.17
$ NODE_ENV=production node build.js
internal/modules/cjs/loader.js:888
  throw err;
  ^

Error: Cannot find module 'rollup'
Require stack:
- /home/pi/UI/qortal-ui-plugins/build.js
- /home/pi/UI/qortal-ui-plugins/default-plugins.js
- /home/pi/UI/qortal-ui/build.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:885:15)
    at Function.Module._load (internal/modules/cjs/loader.js:730:27)
    at Module.require (internal/modules/cjs/loader.js:957:19)
    at require (internal/modules/cjs/helpers.js:88:18)
    at Object.<anonymous> (/home/pi/UI/qortal-ui-plugins/build.js:1:16)
    at Module._compile (internal/modules/cjs/loader.js:1068:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1097:10)
    at Module.load (internal/modules/cjs/loader.js:933:32)
    at Function.Module._load (internal/modules/cjs/loader.js:774:14)
    at Module.require (internal/modules/cjs/loader.js:957:19) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/home/pi/UI/qortal-ui-plugins/build.js',
    '/home/pi/UI/qortal-ui-plugins/default-plugins.js',
    '/home/pi/UI/qortal-ui/build.js'
  ]
}
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

ive run npm install --global rollup and installed that

same error eveeytime i try it

**Comment by AlphaX-Projects** [comment]
Best way is to use appimage on Pi
